

services:
  postgres-main:
    image: postgres:latest
    container_name: postgres-main
    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: maincataloguedb

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql

    networks:
      - backend-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123

    ports:
      - "8080:80"

    depends_on:
      - postgres-main

    networks:
      - backend-network

  

  postgres-client:
    image: postgres:latest

    container_name: postgres-client

    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: client1_db

    ports:
      - "5433:5433"

    volumes:
      - postgres-data:/var/lib/postgresql

    networks:
      - backend-network
networks:
  backend-network:

volumes:
  postgres-data: