version: '3.9'

services:
  postgres-main:
    image: postgres:16
    container_name: postgres-main
    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: maincataloguedb

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - backend-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123

    ports:
      - "8080:80"

    depends_on:
      - postgres-main

    networks:
      - backend-network

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: myapp-api

    ports:
      - "8080:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings__DefaultConnection: Host=postgres-db;Port=5432;Database=myappdb;Username=admin;Password=secret123

    depends_on:
      - postgres

    networks:
      - backend-network

  postgres:
    image: postgres:16

    container_name: postgres-db

    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: myappdb

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - backend-network
networks:
  backend-network:

volumes:
  postgres-data: